---
title: "Dodatak (Izračunavanje kvantila koristeći različite metode)"
output:
  html_document:
    df_print: paged
---

```{r}

x <- c(185, 162, 170, 172, 190, 180, 163, 157, 180, 205)
x <- sort(x)

p = 0.75
n <- length(x)
index <- 1 + (n - 1) * p
l <- floor(index)
h <- ceiling(index)
diff <- index - l
q <- (1 - diff) * x[l] + diff * x[h]

cat("p =", p, "\n")
cat("n =", n, "\n")
cat("index =", index, "\n")
cat("l =", l, "\n")
cat("h =", h, "\n")
cat("diff =", diff, "\n")
cat("q =", q)
```

```{r}

library(tidyverse)

x <- c(185, 162, 170, 172, 190, 180, 163, 157, 180, 205)
quantiles <- quantile(x, type = 1)
quantiles2 <- quantile(x, type = 7)
df <- data.frame(
  x = 1,
  y0 = quantiles[1],
  y25 = quantiles[2],
  y50 = quantiles[3],
  y75 = quantiles[4],
  y100 = quantiles[5]
)

quantiles <- quantile(x, type = 7)
df2 <- data.frame(
  x = 1,
  y0 = quantiles[1],
  y25 = quantiles[2],
  y50 = quantiles[3],
  y75 = quantiles[4],
  y100 = quantiles[5]
)

ggplot(df, aes(x)) +
  geom_boxplot(
   aes(ymin = y0, lower = y25, middle = y50, upper = y75, ymax = y100),
   stat = "identity",
   width = 0.7
 ) + scale_x_discrete( ) + ggtitle("Dvostruki medijan")
ggplot(df2, aes(x)) +
  geom_boxplot(
   aes(ymin = y0, lower = y25, middle = y50, upper = y75, ymax = y100),
   stat = "identity",
   width = 0.7
 ) + scale_x_discrete( ) + ggtitle("Interpolacija")
```
